# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: announcement.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from generic.api import configuration_pb2 as configuration__pb2
from generic.api import label_pb2 as label__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61nnouncement.proto\x12\x11PluginAdapter.Api\x1a\x13\x63onfiguration.proto\x1a\x0blabel.proto\"\x7f\n\x0c\x41nnouncement\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x37\n\rconfiguration\x18\x02 \x01(\x0b\x32 .PluginAdapter.Api.Configuration\x12(\n\x06labels\x18\x03 \x03(\x0b\x32\x18.PluginAdapter.Api.Labelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'announcement_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ANNOUNCEMENT']._serialized_start=75
  _globals['_ANNOUNCEMENT']._serialized_end=202
# @@protoc_insertion_point(module_scope)
