# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: announcements.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from adapter.generic.api import announcement_pb2 as announcement__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61nnouncements.proto\x12\x11PluginAdapter.Api\x1a\x12\x61nnouncement.proto\"G\n\rAnnouncements\x12\x36\n\rannouncements\x18\x01 \x03(\x0b\x32\x1f.PluginAdapter.Api.Announcementb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'announcements_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ANNOUNCEMENTS']._serialized_start=62
  _globals['_ANNOUNCEMENTS']._serialized_end=133
# @@protoc_insertion_point(module_scope)
