# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: label.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blabel.proto\x12\x11PluginAdapter.Api\"\xa1\x07\n\x05Label\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\".PluginAdapter.Api.Label.LabelType\x12\r\n\x05label\x18\x02 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\t\x12\x36\n\nparameters\x18\x04 \x03(\x0b\x32\".PluginAdapter.Api.Label.Parameter\x12\x11\n\ttimestamp\x18\x05 \x01(\x04\x12\x16\n\x0ephysical_label\x18\x06 \x01(\x0c\x12\x16\n\x0e\x63orrelation_id\x18\x07 \x01(\x04\x1a\xa1\x05\n\tParameter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.PluginAdapter.Api.Label.Parameter.Value\x1a\xcc\x04\n\x05Value\x12\x10\n\x06string\x18\x01 \x01(\tH\x00\x12\x11\n\x07integer\x18\x02 \x01(\x03H\x00\x12\x11\n\x07\x64\x65\x63imal\x18\x03 \x01(\x01H\x00\x12\x11\n\x07\x62oolean\x18\x04 \x01(\x08H\x00\x12\x0e\n\x04\x64\x61te\x18\x05 \x01(\x04H\x00\x12\x0e\n\x04time\x18\t \x01(\x04H\x00\x12?\n\x05\x61rray\x18\x06 \x01(\x0b\x32..PluginAdapter.Api.Label.Parameter.Value.ArrayH\x00\x12?\n\x06struct\x18\x07 \x01(\x0b\x32-.PluginAdapter.Api.Label.Parameter.Value.HashH\x00\x12\x43\n\nhash_value\x18\x08 \x01(\x0b\x32-.PluginAdapter.Api.Label.Parameter.Value.HashH\x00\x1a\x41\n\x05\x41rray\x12\x38\n\x06values\x18\x01 \x03(\x0b\x32(.PluginAdapter.Api.Label.Parameter.Value\x1a\xc5\x01\n\x04Hash\x12\x44\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x33.PluginAdapter.Api.Label.Parameter.Value.Hash.Entry\x1aw\n\x05\x45ntry\x12\x35\n\x03key\x18\x01 \x01(\x0b\x32(.PluginAdapter.Api.Label.Parameter.Value\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.PluginAdapter.Api.Label.Parameter.ValueB\x06\n\x04type\"\'\n\tLabelType\x12\x0c\n\x08STIMULUS\x10\x00\x12\x0c\n\x08RESPONSE\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'label_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_LABEL']._serialized_start=35
  _globals['_LABEL']._serialized_end=964
  _globals['_LABEL_PARAMETER']._serialized_start=250
  _globals['_LABEL_PARAMETER']._serialized_end=923
  _globals['_LABEL_PARAMETER_VALUE']._serialized_start=335
  _globals['_LABEL_PARAMETER_VALUE']._serialized_end=923
  _globals['_LABEL_PARAMETER_VALUE_ARRAY']._serialized_start=650
  _globals['_LABEL_PARAMETER_VALUE_ARRAY']._serialized_end=715
  _globals['_LABEL_PARAMETER_VALUE_HASH']._serialized_start=718
  _globals['_LABEL_PARAMETER_VALUE_HASH']._serialized_end=915
  _globals['_LABEL_PARAMETER_VALUE_HASH_ENTRY']._serialized_start=796
  _globals['_LABEL_PARAMETER_VALUE_HASH_ENTRY']._serialized_end=915
  _globals['_LABEL_LABELTYPE']._serialized_start=925
  _globals['_LABEL_LABELTYPE']._serialized_end=964
# @@protoc_insertion_point(module_scope)
