# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from generic.api import label_pb2 as label__pb2
from generic.api import announcement_pb2 as announcement__pb2
from generic.api import configuration_pb2 as configuration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x11PluginAdapter.Api\x1a\x0blabel.proto\x1a\x12\x61nnouncement.proto\x1a\x13\x63onfiguration.proto\"\xf5\x02\n\x07Message\x12\x31\n\x05\x65rror\x18\x01 \x01(\x0b\x32 .PluginAdapter.Api.Message.ErrorH\x00\x12\x37\n\x0c\x61nnouncement\x18\x02 \x01(\x0b\x32\x1f.PluginAdapter.Api.AnnouncementH\x00\x12\x39\n\rconfiguration\x18\x03 \x01(\x0b\x32 .PluginAdapter.Api.ConfigurationH\x00\x12)\n\x05label\x18\x04 \x01(\x0b\x32\x18.PluginAdapter.Api.LabelH\x00\x12\x31\n\x05reset\x18\x05 \x01(\x0b\x32 .PluginAdapter.Api.Message.ResetH\x00\x12\x31\n\x05ready\x18\x06 \x01(\x0b\x32 .PluginAdapter.Api.Message.ReadyH\x00\x1a\x07\n\x05Reset\x1a\x07\n\x05Ready\x1a\x18\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\tB\x06\n\x04typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=91
  _globals['_MESSAGE']._serialized_end=464
  _globals['_MESSAGE_RESET']._serialized_start=414
  _globals['_MESSAGE_RESET']._serialized_end=421
  _globals['_MESSAGE_READY']._serialized_start=423
  _globals['_MESSAGE_READY']._serialized_end=430
  _globals['_MESSAGE_ERROR']._serialized_start=432
  _globals['_MESSAGE_ERROR']._serialized_end=456
# @@protoc_insertion_point(module_scope)
